function Xfilt = bandPassFilter(X,low,high,SampleInterval)
%this is not really correct
Xfilt = edu.washington.riekelab.patterson.utils.lowPassFilter(...
    edu.washington.riekelab.patterson.utils.highPassFilter(X,low,SampleInterval),...
    high,SampleInterval);